global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:9464']  # Use service name instead of host.docker.internal

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']  # Scrape OTEL collector metrics
